### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AHACKER5** [Vazity1337/Discord-IP-Grabber#1]
Hi! I keep attempting to run this (for testing) in the cmd prompt using 'python Discord-ip-grabber.py' and get this error -

  File "Discord-ip-grabber.py", line 11
    r = requests.get(f'http://extreme-ip-lookup.com/json/{ip}')
                                                                                               ^
SyntaxError: invalid syntax

can anyone help?

**Comment by scrazzz** [comment]
Just don't.
Don't use this if you don't know how to use python.

and by saying "*I keep attempting to run this* (**for testing**)..", it's obvious you're not using it for testing.

**Comment by AHACKER5** [comment]
I was testing this to see if it would work? and as i can see it doesnt

**Comment by devkevin-coder** [comment]
This is really nice script vazity its well written and mostly it actuallt works i also would love to collborate with you in teams.

**Comment by Vazity1337** [comment]
> This is really nice script vazity its well written and mostly it actuallt works i also would love to collborate with you in teams.

Add me on Discord: Vazity#1337 :)

**Comment by devkevin-coder** [comment]
> Hi! I keep attempting to run this (for testing) in the cmd prompt using 'python Discord-ip-grabber.py' and get this error -
> 
> File "Discord-ip-grabber.py", line 11
> r = requests.get(f'[http://extreme-ip-lookup.com/json/{ip}](http://extreme-ip-lookup.com/json/%7Bip%7D)')
> ^
> SyntaxError: invalid syntax
> 
> can anyone help?

I can help you, i made a Discord IpGrabber but i have to uplaod it to github.
